#Animation Assets
#animation = pygame.image.load("resources/animation/explosion.gif")
scene1 = pygame.image.load("resources/explosion/scene1.jpg")
scene2 = pygame.image.load("resources/explosion/scene2.jpg")
scene3 = pygame.image.load("resources/explosion/scene3.jpg")
scene4 = pygame.image.load("resources/explosion/scene4.jpg")
scene5 = pygame.image.load("resources/explosion/scene5.jpg")
scene6 = pygame.image.load("resources/explosion/scene6.jpg")
scene7 = pygame.image.load("resources/explosion/scene7.jpg")
scene8 = pygame.image.load("resources/explosion/scene8.jpg")
scene9 = pygame.image.load("resources/explosion/scene9.jpg")
scene10 = pygame.image.load("resources/explosion/scene10.jpg")
scene11 = pygame.image.load("resources/explosion/scene11.jpg")
scene12 = pygame.image.load("resources/explosion/scene12.jpg")
scene14 = pygame.image.load("resources/explosion/scene14.jpg")
scene15 = pygame.image.load("resources/explosion/scene15.jpg")
scene16 = pygame.image.load("resources/explosion/scene16.jpg")
scene17 = pygame.image.load("resources/explosion/scene17.jpg")
scene18 = pygame.image.load("resources/explosion/scene18.jpg")
scene19 = pygame.image.load("resources/explosion/scene19.jpg")
scene20 = pygame.image.load("resources/explosion/scene20.jpg")
scene21 = pygame.image.load("resources/explosion/scene21.jpg")
scene22 = pygame.image.load("resources/explosion/scene22.jpg")
scene23 = pygame.image.load("resources/explosion/scene23.jpg")
scene24 = pygame.image.load("resources/explosion/scene24.jpg")
scene25 = pygame.image.load("resources/explosion/scene25.jpg")
scene26 = pygame.image.load("resources/explosion/scene26.jpg")
scene27 = pygame.image.load("resources/explosion/scene27.jpg")

##def animation():
##    animationplay = True
##
##    if animationplay:
##        print(animationplay)
##        gameDisplay.blit(scene1, (0,0))
##        time.sleep(0.1)
##        pygame.display.update()
##        gameDisplay.blit(scene2, (0,0))
##        time.sleep(0.1)
##        pygame.display.update()
##        gameDisplay.blit(scene3, (0,0))
##        time.sleep(0.1)
##        pygame.display.update()
##        gameDisplay.blit(scene4, (0,0))
##        time.sleep(0.1)
##        pygame.display.update()
##        gameDisplay.blit(scene5, (0,0))
##        time.sleep(0.1)
##        pygame.display.update()
##        gameDisplay.blit(scene6, (0,0))
##        time.sleep(0.1)
##        pygame.display.update()
##        gameDisplay.blit(scene7, (0,0))
##        time.sleep(0.1)
##        pygame.display.update()
##        gameDisplay.blit(scene8, (0,0))
##        time.sleep(0.1)
##        pygame.display.update()
##        gameDisplay.blit(scene9, (0,0))
##        time.sleep(0.1)
##        pygame.display.update()
##        gameDisplay.blit(scene10, (0,0))
##        time.sleep(0.1)
##        pygame.display.update()
##        gameDisplay.blit(scene11, (0,0))
##        time.sleep(0.1)
##        pygame.display.update()
##        gameDisplay.blit(scene12, (0,0))
##        time.sleep(0.1)
##        pygame.display.update()
##        #gameDisplay.blit(scene13, (0,0))
##        #time.sleep(1)
##        #pygame.display.update()
##        gameDisplay.blit(scene14, (0,0))
##        time.sleep(0.1)
##        pygame.display.update()
##        gameDisplay.blit(scene15, (0,0))
##        time.sleep(0.1)
##        pygame.display.update()
##        gameDisplay.blit(scene16, (0,0))
##        time.sleep(0.1)
##        pygame.display.update()
##        gameDisplay.blit(scene17, (0,0))
##        time.sleep(0.1)
##        pygame.display.update()
##        gameDisplay.blit(scene18, (0,0))
##        time.sleep(0.1)
##        pygame.display.update()
##        gameDisplay.blit(scene19, (0,0))
##        time.sleep(0.1)
##        pygame.display.update()
##        gameDisplay.blit(scene20, (0,0))
##        time.sleep(0.1)
##        pygame.display.update()
##        gameDisplay.blit(scene21, (0,0))
##        time.sleep(0.1)
##        pygame.display.update()
##        gameDisplay.blit(scene22, (0,0))
##        time.sleep(0.1)
##        pygame.display.update()
##        gameDisplay.blit(scene23, (0,0))
##        time.sleep(0.1)
##        pygame.display.update()
##        gameDisplay.blit(scene24, (0,0))
##        time.sleep(0.1)
##        pygame.display.update()
##        gameDisplay.blit(scene25, (0,0))
##        time.sleep(0.1)
##        pygame.display.update()
##        gameDisplay.blit(scene26, (0,0))
##        time.sleep(0.1)
##        pygame.display.update()
##        gameDisplay.blit(scene27, (0,0))
##        time.sleep(0.1)
##        pygame.display.update()
##        animationplay = False
##    elif animationplay == False:
##        game_loop()      
